### ISSUE TITLE
Incorrect Type in settings.json

### ISSUE THREAD

**Issue by ahakki** [hoovercj/vscode-haskell-linter#11]
The default Value for haskell.hlint.executablePath (null) causes a permanent irremovable Warning to appear in the lower Info bar due to "incorrect type". Changing the Value in the User Settings does not remove the Error Message.

See attached Screenshot for Info
![Screenshot](https://cloud.githubusercontent.com/assets/12851637/15150710/ad757af4-16ce-11e6-870c-4606669e917e.png)

**Comment by hoovercj** [comment]
Thanks for letting me know! I just published a fix. Please reopen this issue if the problem persists.
