### ISSUE TITLE
Not all errors get underlined

### ISSUE THREAD

**Issue by ghost** [hoovercj/vscode-haskell-linter#14]
https://github.com/hoovercj/vscode-ghc-mod/issues/42
This probably belongs here instead of the ghc-mod extension

I notice that if you have an error at the top of the file, errors further in the file will not be underlined.

Test case:

```
module Test where

import  Test.QuickCheck.Checkers 
import  Web.Scotty
import  Test.QuickCheck
import  Test.sdasad

data List a =
    Nil
    | Cons a (List a)
    deriving (Eq, Showasdadasdasda)

data List a = asda
```

import Test.sdasad is underlined as it should be, but the errors at the bottom are not.

**Comment by hoovercj** [comment]
What happens if you run hlint from the command line?

I get:

```
hlint .\src\Test.hs
.\src\Test.hs:6:9: Error: Parse error: Test.sdasad
Found:
    import  Web.Scotty
    import  Test.QuickCheck
  > import  Test.sdasad

    data List a =

1 hint
```

I don't know what else I can do if this is all that hlint gives me.

**Comment by ghost** [comment]
Understood.  After further investigation this is how other editors work too in haskell.  It just seems a bit odd coming from a .NET background.  Thanks.
