### ISSUE TITLE
Configure hlinter from build-tool-depends

### ISSUE THREAD

**Issue by przemo-hemmersbach** [hoovercj/vscode-haskell-linter#35]
With hlint in build-tool-depends, hlint can be build as local dependency of package and can then be run as `cabal run hlint`.

Is there a way to configure extension to call hlint like that?

**Comment by Gerhood** [comment]
See also #17

**Comment by przemo-hemmersbach** [comment]
After seeing #17, I think this issue is duplicate for all practical purposes, as any solution that allows custom executor will be executor agnostic.
